### ISSUE TITLE
Newbie Question

### ISSUE THREAD

**Issue by alanflex** [readdle/swift-windows-gha#52]
Hi, I have a working swift compiler on Windows from following the Apple instructions and (separately) I have a working setup building some cross-platform ObjC using clang and cmake and gnustep. 

In the readme for this repo it suggests that it will install clang modules for swift in the MSVC installation which I am *hoping* means I could end up being able to run a single build train that uses the system clang to compile ObjC and Swift and is clever enough to understand the references between them.

Have you ever heard of anyone doing something like this ?  I'm somewhat of newbie doing this stuff outside of Xcode :-)

**Comment by lxbndr** [comment]
Wow, that's sounds like an adventure :-) You probably could try clang from Swift toolchain. But I guess that it is impossible to achieve Darwin level of ObjC-Swift interoperability on Windows, as such interop is completely relies on specific Apple version of ObjC Foundation framework with special Swift overlay. And most of ObjC interop code is disabled in Swift on Windows.

I don't know anyone who did similar work, but I believe you could post a question on Swift forums. There are many specialists who are involved in Swift and Swift on Windows, like @compnerd.

**Comment by alanflex** [comment]
Thanks folks, I think we'll step back and work out an FFI shell in C around the objC. :-)

**Comment by triplef** [comment]
Might also be worth checking on the GNUstep mailing list if anyone has looked into ObjC/Swift interop with the GNUstep Objective-C runtime (aka libobjc2) and frameworks.

I’m agreeing with @lxbndr though that this would be uncharted territory and will definitely not work out of the box right now. For that reason we’re sticking to Objective-C on Windows, also in order to avoid further increasing the complexity of the toolchain.

**Comment by alanflex** [comment]
I did a bunch of looking around through swift mailing lists etc and there's lots of talk about it, but it seems to very much Not A Priority for the swift team.  

https://forums.swift.org/t/state-of-gnustep-interop/50950/6

https://forums.swift.org/t/proposal-swift-open-source-project-and-foundation-replacements/66/1

**Comment by triplef** [comment]
Interesting, thanks for the links. I think you’re right about that assessment... 😕
